package de.develappers.facerecognition.serviceAI.faceServiceAI.model

class FaceLandmark {
    var contour_left1: Point? = null
    var contour_left2: Point? = null
    var contour_left3: Point? = null
    var contour_left4: Point? = null
    var contour_left5: Point? = null
    var contour_left6: Point? = null
    var contour_left7: Point? = null
    var contour_left8: Point? = null
    var contour_left9: Point? = null
    var contour_left10: Point? = null
    var contour_left11: Point? = null
    var contour_left12: Point? = null
    var contour_left13: Point? = null
    var contour_left14: Point? = null
    var contour_left15: Point? = null
    var contour_left16: Point? = null
    var contour_chin: Point? = null
    var contour_right1: Point? = null
    var contour_right2: Point? = null
    var contour_right3: Point? = null
    var contour_right4: Point? = null
    var contour_right5: Point? = null
    var contour_right6: Point? = null
    var contour_right7: Point? = null
    var contour_right8: Point? = null
    var contour_right9: Point? = null
    var contour_right10: Point? = null
    var contour_right11: Point? = null
    var contour_right12: Point? = null
    var contour_right13: Point? = null
    var contour_right14: Point? = null
    var contour_right15: Point? = null
    var contour_right16: Point? = null
    var left_eyebrow_left_corner: Point? = null
    var left_eyebrow_upper_left_quarter: Point? = null
    var left_eyebrow_upper_middle: Point? = null
    var left_eyebrow_upper_right_quarter: Point? = null
    var left_eyebrow_upper_right_corner: Point? = null
    var left_eyebrow_lower_left_quarter: Point? = null
    var left_eyebrow_lower_middle: Point? = null
    var left_eyebrow_lower_right_quarter: Point? = null
    var left_eyebrow_lower_right_corner: Point? = null
    var right_eyebrow_upper_left_corner: Point? = null
    var right_eyebrow_upper_left_quarter: Point? = null
    var right_eyebrow_upper_middle: Point? = null
    var right_eyebrow_upper_right_quarter: Point? = null
    var right_eyebrow_right_corner: Point? = null
    var right_eyebrow_lower_left_corner: Point? = null
    var right_eyebrow_lower_left_quarter: Point? = null
    var right_eyebrow_lower_middle: Point? = null
    var right_eyebrow_lower_right_quarter: Point? = null
    var nose_bridge1: Point? = null
    var nose_bridge2: Point? = null
    var nose_bridge3: Point? = null
    var nose_tip: Point? = null
    var nose_left_contour1: Point? = null
    var nose_left_contour2: Point? = null
    var nose_left_contour3: Point? = null
    var nose_left_contour4: Point? = null
    var nose_left_contour5: Point? = null
    var nose_middle_contour: Point? = null
    var nose_right_contour1: Point? = null
    var nose_right_contour2: Point? = null
    var nose_right_contour3: Point? = null
    var nose_right_contour4: Point? = null
    var nose_right_contour5: Point? = null
    var left_eye_left_corner: Point? = null
    var left_eye_upper_left_quarter: Point? = null
    var left_eye_top: Point? = null
    var left_eye_upper_right_quarter: Point? = null
    var left_eye_right_corner: Point? = null
    var left_eye_lower_right_quarter: Point? = null
    var left_eye_bottom: Point? = null
    var left_eye_lower_left_quarter: Point? = null
    var left_eye_pupil: Point? = null
    var left_eye_center: Point? = null
    var right_eye_left_corner: Point? = null
    var right_eye_upper_left_quarter: Point? = null
    var right_eye_top: Point? = null
    var right_eye_upper_right_quarter: Point? = null
    var right_eye_right_corner: Point? = null
    var right_eye_lower_right_quarter: Point? = null
    var right_eye_bottom: Point? = null
    var right_eye_lower_left_quarter: Point? = null
    var right_eye_pupil: Point? = null
    var right_eye_center: Point? = null
    var mouth_left_corner: Point? = null
    var mouth_upper_lip_left_contour1: Point? = null
    var mouth_upper_lip_left_contour2: Point? = null
    var mouth_upper_lip_left_contour3: Point? = null
    var mouth_upper_lip_left_contour4: Point? = null
    var mouth_right_corner: Point? = null
    var mouth_upper_lip_right_contour1: Point? = null
    var mouth_upper_lip_right_contour2: Point? = null
    var mouth_upper_lip_right_contour3: Point? = null
    var mouth_upper_lip_right_contour4: Point? = null
    var mouth_upper_lip_top: Point? = null
    var mouth_upper_lip_bottom: Point? = null
    var mouth_lower_lip_right_contour1: Point? = null
    var mouth_lower_lip_right_contour2: Point? = null
    var mouth_lower_lip_right_contour3: Point? = null
    var mouth_lower_lip_left_contour1: Point? = null
    var mouth_lower_lip_left_contour2: Point? = null
    var mouth_lower_lip_left_contour3: Point? = null
    var mouth_lower_lip_top: Point? = null
    var mouth_lower_lip_bottom: Point? = null

    override fun toString(): String {
        return "{" +
                "\"contour_left1\":" + contour_left1 +
                ", \"contour_left2\":" + contour_left2 +
                ", \"contour_left3\":" + contour_left3 +
                ", \"contour_left4\":" + contour_left4 +
                ", \"contour_left5\":" + contour_left5 +
                ", \"contour_left6\":" + contour_left6 +
                ", \"contour_left7\":" + contour_left7 +
                ", \"contour_left8\":" + contour_left8 +
                ", \"contour_left9\":" + contour_left9 +
                ", \"contour_left10\":" + contour_left10 +
                ", \"contour_left11\":" + contour_left11 +
                ", \"contour_left12\":" + contour_left12 +
                ", \"contour_left13\":" + contour_left13 +
                ", \"contour_left14\":" + contour_left14 +
                ", \"contour_left15\":" + contour_left15 +
                ", \"contour_left16\":" + contour_left16 +
                ", \"contour_chin\":" + contour_chin +
                ", \"contour_right1\":" + contour_right1 +
                ", \"contour_right2\":" + contour_right2 +
                ", \"contour_right3\":" + contour_right3 +
                ", \"contour_right4\":" + contour_right4 +
                ", \"contour_right5\":" + contour_right5 +
                ", \"contour_right6\":" + contour_right6 +
                ", \"contour_right7\":" + contour_right7 +
                ", \"contour_right8\":" + contour_right8 +
                ", \"contour_right9\":" + contour_right9 +
                ", \"contour_right10\":" + contour_right10 +
                ", \"contour_right11\":" + contour_right11 +
                ", \"contour_right12\":" + contour_right12 +
                ", \"contour_right13\":" + contour_right13 +
                ", \"contour_right14\":" + contour_right14 +
                ", \"contour_right15\":" + contour_right15 +
                ", \"contour_right16\":" + contour_right16 +
                ", \"left_eyebrow_left_corner\":" + left_eyebrow_left_corner +
                ", \"left_eyebrow_upper_left_quarter\":" + left_eyebrow_upper_left_quarter +
                ", \"left_eyebrow_upper_middle\":" + left_eyebrow_upper_middle +
                ", \"left_eyebrow_upper_right_quarter\":" + left_eyebrow_upper_right_quarter +
                ", \"left_eyebrow_upper_right_corner\":" + left_eyebrow_upper_right_corner +
                ", \"left_eyebrow_lower_left_quarter\":" + left_eyebrow_lower_left_quarter +
                ", \"left_eyebrow_lower_middle\":" + left_eyebrow_lower_middle +
                ", \"left_eyebrow_lower_right_quarter\":" + left_eyebrow_lower_right_quarter +
                ", \"left_eyebrow_lower_right_corner\":" + left_eyebrow_lower_right_corner +
                ", \"right_eyebrow_upper_left_corner\":" + right_eyebrow_upper_left_corner +
                ", \"right_eyebrow_upper_left_quarter\":" + right_eyebrow_upper_left_quarter +
                ", \"right_eyebrow_upper_middle\":" + right_eyebrow_upper_middle +
                ", \"right_eyebrow_upper_right_quarter\":" + right_eyebrow_upper_right_quarter +
                ", \"right_eyebrow_right_corner\":" + right_eyebrow_right_corner +
                ", \"right_eyebrow_lower_left_corner\":" + right_eyebrow_lower_left_corner +
                ", \"right_eyebrow_lower_left_quarter\":" + right_eyebrow_lower_left_quarter +
                ", \"right_eyebrow_lower_middle\":" + right_eyebrow_lower_middle +
                ", \"right_eyebrow_lower_right_quarter\":" + right_eyebrow_lower_right_quarter +
                ", \"nose_bridge1\":" + nose_bridge1 +
                ", \"nose_bridge2\":" + nose_bridge2 +
                ", \"nose_bridge3\":" + nose_bridge3 +
                ", \"nose_tip\":" + nose_tip +
                ", \"nose_left_contour1\":" + nose_left_contour1 +
                ", \"nose_left_contour2\":" + nose_left_contour2 +
                ", \"nose_left_contour3\":" + nose_left_contour3 +
                ", \"nose_left_contour4\":" + nose_left_contour4 +
                ", \"nose_left_contour5\":" + nose_left_contour5 +
                ", \"nose_middle_contour\":" + nose_middle_contour +
                ", \"nose_right_contour1\":" + nose_right_contour1 +
                ", \"nose_right_contour2\":" + nose_right_contour2 +
                ", \"nose_right_contour3\":" + nose_right_contour3 +
                ", \"nose_right_contour4\":" + nose_right_contour4 +
                ", \"nose_right_contour5\":" + nose_right_contour5 +
                ", \"left_eye_left_corner\":" + left_eye_left_corner +
                ", \"left_eye_upper_left_quarter\":" + left_eye_upper_left_quarter +
                ", \"left_eye_top\":" + left_eye_top +
                ", \"left_eye_upper_right_quarter\":" + left_eye_upper_right_quarter +
                ", \"left_eye_right_corner\":" + left_eye_right_corner +
                ", \"left_eye_lower_right_quarter\":" + left_eye_lower_right_quarter +
                ", \"left_eye_bottom\":" + left_eye_bottom +
                ", \"left_eye_lower_left_quarter\":" + left_eye_lower_left_quarter +
                ", \"left_eye_pupil\":" + left_eye_pupil +
                ", \"left_eye_center\":" + left_eye_center +
                ", \"right_eye_left_corner\":" + right_eye_left_corner +
                ", \"right_eye_upper_left_quarter\":" + right_eye_upper_left_quarter +
                ", \"right_eye_top\":" + right_eye_top +
                ", \"right_eye_upper_right_quarter\":" + right_eye_upper_right_quarter +
                ", \"right_eye_right_corner\":" + right_eye_right_corner +
                ", \"right_eye_lower_right_quarter\":" + right_eye_lower_right_quarter +
                ", \"right_eye_bottom\":" + right_eye_bottom +
                ", \"right_eye_lower_left_quarter\":" + right_eye_lower_left_quarter +
                ", \"right_eye_pupil\":" + right_eye_pupil +
                ", \"right_eye_center\":" + right_eye_center +
                ", \"mouth_left_corner\":" + mouth_left_corner +
                ", \"mouth_upper_lip_left_contour1\":" + mouth_upper_lip_left_contour1 +
                ", \"mouth_upper_lip_left_contour2\":" + mouth_upper_lip_left_contour2 +
                ", \"mouth_upper_lip_left_contour3\":" + mouth_upper_lip_left_contour3 +
                ", \"mouth_upper_lip_left_contour4\":" + mouth_upper_lip_left_contour4 +
                ", \"mouth_right_corner\":" + mouth_right_corner +
                ", \"mouth_upper_lip_right_contour1\":" + mouth_upper_lip_right_contour1 +
                ", \"mouth_upper_lip_right_contour2\":" + mouth_upper_lip_right_contour2 +
                ", \"mouth_upper_lip_right_contour3\":" + mouth_upper_lip_right_contour3 +
                ", \"mouth_upper_lip_right_contour4\":" + mouth_upper_lip_right_contour4 +
                ", \"mouth_upper_lip_top\":" + mouth_upper_lip_top +
                ", \"mouth_upper_lip_bottom\":" + mouth_upper_lip_bottom +
                ", \"mouth_lower_lip_right_contour1\":" + mouth_lower_lip_right_contour1 +
                ", \"mouth_lower_lip_right_contour2\":" + mouth_lower_lip_right_contour2 +
                ", \"mouth_lower_lip_right_contour3\":" + mouth_lower_lip_right_contour3 +
                ", \"mouth_lower_lip_left_contour1\":" + mouth_lower_lip_left_contour1 +
                ", \"mouth_lower_lip_left_contour2\":" + mouth_lower_lip_left_contour2 +
                ", \"mouth_lower_lip_left_contour3\":" + mouth_lower_lip_left_contour3 +
                ", \"mouth_lower_lip_top\":" + mouth_lower_lip_top +
                ", \"mouth_lower_lip_bottom\":" + mouth_lower_lip_bottom +
                '}'
    }

    class Point {
        var x = 0
        var y = 0

        override fun toString(): String {
            return "Point{" +
                    "x=" + x +
                    ", y=" + y +
                    '}'
        }
    }
}